### ISSUE TITLE
Sample app fails to update nrf52840

### ISSUE THREAD

**Issue by GiulianoFranchetto** [JuulLabs-OSS/mcumgr-android#49]
Hi,

I tried the sample application to flash a nrf52840 board. However, when I start the DFU, the request goes in timeout.

The "echo" function works, so we are indeed connected to the nrf52.

Will this library be usable with the nrf52840? If so, do you have a milestone for it?

Regards

**Comment by philips77** [comment]
Hello, 
It should work with nRF52840 running Zephyr and SMP Server sample. 
At what time did you get the timeout?

nRF52840, due to its flash hardware, requires a lot of time to erase pages. For an app around 120 kb it takes 10 seconds which has to be multiplied by 2 if the connection is open, as 50% of time is reserved to keep the connection open. The new version of the app specifies the swap time to be 
https://github.com/JuulLabs-OSS/mcumgr-android/blob/506405483d990d9ef36c9daecc73cf3aaf4ac34b/sample/src/main/java/io/runtime/mcumgr/sample/viewmodel/mcumgr/ImageUpgradeViewModel.java#L70
This is required when the slot 1 is being erased, that is either before the upload, or during swapping slots.

Could you pose logs here?

**Comment by GiulianoFranchetto** [comment]
Hello,

Where can I find the log? Logcat, or is there a place in the app?
I get a "timeout" after clicking on the "start" button on the DFU page.

**Comment by philips77** [comment]
Yes, LogCat. By default it logs when in DEBUG.
