### ISSUE TITLE
About License

### ISSUE THREAD

**Issue by jnpStimio** [JuulLabs-OSS/mcumgr-android#69]
Hello,

Firstly, thank you for this nice project.
I would like to get some information about licensing ? I suppose it is under BSD like your [BLE lib dependency](https://github.com/NordicSemiconductor/Android-BLE-Library/tree/develop) ?

**Comment by bgiori** [comment]
Hi @jnpStimio, thank you for the kind words!

McuManager is licensed under `Apache 2.0` (I should probably add this to the README).

The BLE library dependency is developed independently by Nordic Semiconductor, hence the license difference.

Let me know if you have additional questions, otherwise, feel free to close the issue.
