### ISSUE TITLE
onUpgradFailed gets called but update continues

### ISSUE THREAD

**Issue by lambo81** [JuulLabs-OSS/mcumgr-android#93]
The callback:

public void onUpgradeFailed(FirmwareUpgradeManager.State state, McuMgrException error);

gets called.  state.toString() is "VALIDATE" and error.getMessage() is "Payload (10 bytes) too long for MTU: 0"

However, the device keeps going through the update process.  The next state is "UPLOAD"

**Comment by philips77** [comment]
Hello,
We also encountered the issue and are looking for a solution. Please, check out https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager for more updates, as this repo has been deprecated.

**Comment by philips77** [comment]
OK, we pinpointed the issue. 
It's the issue in BLE library 2.3. This happens when you are already connected to the device using another client (`BluetoothGatt` or `BleManager`), which has requested MTU change. Then, when you connect using `McuMgrBleTransport`, the `onMtuChanged(..)` callback gets fired automatically even before the service discovery begins and, as initialization queue has not yet been initialized, if reports the device as ready here: https://github.com/NordicSemiconductor/Android-BLE-Library/blob/1c8339013e678a864302209618435de5707207dd/ble/src/main/java/no/nordicsemi/android/ble/BleManagerHandler.java#L2357

**Comment by lambo81** [comment]
Wow thank you for your help.  I will try this.

Incidentally, I looked at the Nordic library but was confused as to whether
it supports Zephyr, which is what I’m using. Do you know about that?

**Comment by lambo81** [comment]
Oh never mind the last email. I was  looking at a different Nordic dfu
library than the one you listed.

**Comment by philips77** [comment]
Version [0.13.0-beta06](https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/releases/tag/0.13.0-beta06) should have this issue fixed. It's now available on Maven Central.
